---
collections:
- name: ansible.posix
  version: ">=1.5.1" # Version range identifiers (default: ``*``)
  source: https://galaxy.ansible.com # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
- name: fedora.linux_system_roles
  version: ">=1.21.0" # Version range identifiers (default: ``*``)
  source: https://galaxy.ansible.com # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
- name: community.general
  version: ">=6.4.0" # Version range identifiers (default: ``*``)
  source: https://galaxy.ansible.com # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
- name: infra.controller_configuration
  version: "2.4.1" # Version range identifiers (default: ``*``)
  source: https://galaxy.ansible.com # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
- name: infra.leapp
  version: "1.1.4" # Version range identifiers (default: ``*``)
  source: https://galaxy.ansible.com # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
- name: https://github.com/heatmiser/ansible-snapshot.git
  type: git
  version: main
- name: infra.lvm_snapshots
  version: "2.0.1" # Version range identifiers (default: ``*``)
  source: https://galaxy.ansible.com # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
...
