---
- name: Get instance details
  hosts: "{{ 'control[0]' | default(omit) }}"
  connection: local
  gather_facts: false
  tasks:
    - name: "Get instance details"
      ansible.builtin.include_role:
        name: heatmiser.ansible_snapshot.aws
        tasks_from: instance/get_instance_details

    - name: Debug output - instance_details
      ansible.builtin.debug:
        msg: "{{ instance_details }}"

    - name: Debug output - instance_details - map(attribute='instance_id')
      ansible.builtin.debug:
        msg: "{{ instance_details.instances | map(attribute='instance_id') | list | unique }}"

    - name: Debug output - instance_details - map(attribute='private_ip_address')
      ansible.builtin.debug:
        msg: "{{ instance_details.instances | map(attribute='private_ip_address') | list | unique }}"
...
