---
- name: Wait for connection...
  ansible.builtin.wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- name: Migrate connections to NetworkManager # noqa command-instead-of-module
  ansible.builtin.shell: |
    set -o pipefail
    nmcli connection migrate
  args:
    executable: /bin/bash
...
