---
- name: Display snapshot details of instance
  hosts: "{{ control[0] | default(omit) }}"
  connection: local
  gather_facts: false
  tasks:
    - name: Display snapshot details in region "{{ ec2_region }}"
      ansible.builtin.include_role:
        name: heatmiser.ansible_snapshot.aws
      vars:
        ec2_instance_action: "get_snapshot_details"
...
