---
- name: Revert snapshot of instance
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Revert instance to snapshot in region "{{ ec2_region }}"
      ansible.builtin.include_role:
        name: heatmiser.ansible_snapshot.aws
      vars:
        ec2_instance_action: "snapshot_revert"
...
